add company: Mia-Platform
italiaremote/awesome-italia-remote pull request #113
Opened 2022-02-28 10:28 UTC by akelity

2022-02-28 10:45 UTC, edoardocostantinidev commented
Hi @akelity, please follow the [contribution guidelines](https://github.com/italiaremote/awesome-italia-remote/blob/main/CONTRIBUTING.md) when submitting a PR. Thanks

2022-02-28 10:46 UTC, edoardocostantinidev requested changes
create a json file inside `data` folder.

2022-02-28 11:29 UTC, akelity commented
Sorry for the mistake, I applied the changes.

2022-03-01 10:24 UTC, alessandromr approved these changes

2022-03-01 10:25 UTC, merged