engage labs and engage it services added
italiaremote/awesome-italia-remote pull request #147
Opened 2022-03-07 17:06 UTC by suxstellino

thank you

2022-03-07 18:11 UTC, edoardocostantinidev requested changes
Hi @suxstellino, files should have the `.json` extension, please fix it so we can approve. Thanks for your contribution!

2022-03-07 19:21 UTC, suxstellino commented
I didn't notice that, sorry

2022-03-08 08:24 UTC, suxstellino commented
Done @edoardocostantinidev

2022-03-08 08:33 UTC, alessandromr approved these changes

2022-03-08 08:33 UTC, merged